# Generated by Django 2.1.7 on 2019-03-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('number_plate', models.CharField(max_length=7)),
                ('price', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('availble', models.BooleanField(default=True)),
            ],
        ),
    ]
