# Generated by Django 2.1.7 on 2019-03-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='availble',
            new_name='available',
        ),
    ]
