# Generated by Django 2.1.7 on 2019-05-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='longitude',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_longitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_longitude',
            field=models.FloatField(default=None),
        ),
    ]
