# Generated by Django 2.1.7 on 2019-05-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190506_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
