# Generated by Django 2.1.7 on 2019-05-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190506_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_price',
            field=models.IntegerField(default=0),
        ),
    ]
