# Generated by Django 2.1.7 on 2019-05-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='actual_price',
            field=models.IntegerField(),
        ),
    ]
