# Generated by Django 2.2 on 2019-05-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='car_license',
            field=models.CharField(default='000000', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.CharField(default='0422222222', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='postcode',
            field=models.CharField(default='3000', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='street_name',
            field=models.CharField(default='Required', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='street_number',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='account',
            name='suburb',
            field=models.CharField(default='Melb', max_length=12),
            preserve_default=False,
        ),
    ]
