# Generated by Django 2.2 on 2019-05-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190511_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='car_license',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='account',
            name='street_number',
            field=models.CharField(max_length=4),
        ),
    ]
