# Generated by Django 2.1.7 on 2019-05-20 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190513_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='car_license',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_license', message='Car License is incorrect', regex='^[0-9]{7}$')]),
        ),
    ]
